### ISSUE TITLE
fails to compile with GLib 2.74.x (Debian 12)

### ISSUE THREAD

**Issue by smcv** [flatpak/xdg-desktop-portal#1726]
### Operating System

Debian 12

### XDG Desktop Portal version

1.20

### XDG Desktop Portal version (Other)

1.20.2 or contemporary version from git main

### Desktop Environment

GNOME

### Expected Behavior

Either a successful build, or a `meson setup` failure because my GLib is an unsupported version

### Current Behavior

```
../src/xdp-portal-impl.c: In function ‘load_installed_portals’:
../src/xdp-portal-impl.c:374:21: warning: implicit declaration of function ‘g_hash_table_steal_all_values’; did you mean ‘g_hash_table_steal_all’? [-Wimplicit-function-declaration]
  374 |   implementations = g_hash_table_steal_all_values (portals);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     g_hash_table_steal_all
../src/xdp-portal-impl.c:374:19: warning: assignment to ‘GPtrArray *’ {aka ‘struct _GPtrArray *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  374 |   implementations = g_hash_table_steal_all_values (portals);
      |                   ^
../src/xdp-portal-impl.c:375:3: warning: implicit declaration of function ‘g_ptr_array_sort_values’; did you mean ‘g_ptr_array_sort’? [-Wimplicit-function-declaration]
  375 |   g_ptr_array_sort_values (implementations, sort_impl_by_use_in_and_name);
      |   ^~~~~~~~~~~~~~~~~~~~~~~
      |   g_ptr_array_sort
```

### Steps to Reproduce

1. Debian 12 system (in particular this has GLib 2.74.x)
2. `sudo apt build-dep xdg-desktop-portal`
3. `meson setup _build -Dprefix=/usr`
4. `meson compile -C _build`

### Anything else we should know?

`meson.build` declares a dependency on GLib 2.72. `g_hash_table_steal_all_values()` and `g_ptr_array_sort_values()` were new in GLib 2.76.

**Comment by smcv** [comment]
For the 1.20.x branch I think it would be best if we can continue to be buildable with the declared GLib version (2.72). I'll send a PR shortly (but note that I can't run the test suite on Debian 12, because its `dbusmock` is too old to have `dbusmock.BusType`).

For `main`, I think it would be fine to bump the minimum GLib to 2.76 and revert the addition of 2.72 compatibility.
